### PR TITLE
Detect Radex 1212 v1

### PR DESCRIPTION
**Pull request by ZeroChaos-**
I only tested/modified radex 1212v1.  Would you like me to add the continue line for v2 as well?  I can also swap to the code style you used in the bug, however, I prefer mine since it allows to leave a comment as to why we are ignoring empty

### CODE REVIEW

**Comment by luigifab** [comment]
This is good, but you need to keep `grep('RADEX')`.

dmesg of my RD1212v2.48:
```
[13494.295276] usb 1-2: new full-speed USB device number 4 using xhci_hcd
[13494.471679] usb 1-2: New USB device found, idVendor=03eb, idProduct=5603, bcdDevice= 1.00
[13494.471707] usb 1-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[13494.471719] usb 1-2: Product: RADEX 1212
[13494.471727] usb 1-2: Manufacturer: QWARTA-RAD
[13494.471734] usb 1-2: SerialNumber: 0001A0000000
[13494.488948] hid-generic 0003:03EB:5603.0007: hiddev1,hidraw4: USB HID v1.00 Device
  [QWARTA-RAD RADEX 1212] on usb-0000:00:10.0-2/input0
```

**dmesg of your RD1212v2.03:**
```
[282336.627034] usb 1-1.3: new full-speed USB device number 24 using xhci_hcd
[282336.718944] usb 1-1.3: New USB device found, idVendor=10c4, idProduct=ea60, bcdDevice= 1.00
[282336.718948] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[282336.718950] usb 1-1.3: Product: CP2102 USB to UART Bridge Controller
[282336.718951] usb 1-1.3: Manufacturer: Silicon Labs
[282336.718952] usb 1-1.3: SerialNumber: 0001
[282337.901111] usbcore: registered new interface driver cp210x
[282337.901121] usbserial: USB Serial support registered for cp210x
[282337.901185] cp210x 1-1.3:1.0: cp210x converter detected
[282337.904024] usb 1-1.3: cp210x converter now attached to ttyUSB0
```

and if I [remember](https://github.com/luigifab/python-radexreader/issues/2#issuecomment-817119762) correctly, with QuartaRad driver on Windows, with `print(serial.tools.list_ports)`
```
C:\Windows\system32>cmd.py readall
COM3 - USB5734 COM Port (COM3)
COM1 - Communications Port (COM1)
COM4 - RADEX ONE (COM4)
```

**Comment by ZeroChaos-** [comment]
I did, it's still there, v2 is defined separately
https://github.com/luigifab/python-radexreader/blob/master/src/radexreader/__init__.py#L48-L58

I only modified the v1 block
https://github.com/luigifab/python-radexreader/blob/master/src/radexreader/__init__.py#L73-L84

**Comment by luigifab** [comment]
I don't remember, but perhaps fixed in v1.2.2.

**Comment by ZeroChaos-** [comment]
confirmed fixed in 1.2.2, thanks!

**Pull request closed without merging**
